FROM node:21-alpine AS build-stage

WORKDIR /web_app

COPY ./package.json ./

COPY ./yarn.lock ./

RUN yarn install

COPY . .

RUN GENERATE_SOURCEMAP=false yarn build

FROM nginx:1.20-alpine

COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf

COPY --from=build-stage /web_app/build /usr/share/nginx/html

EXPOSE 3000