name: Build application
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build 
    runs-on: ubuntu-latest
    env:
      PRODUCTION: true
    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Github Packages
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build and push
      uses: docker/bake-action@v3
      with:
        push: true
        files: compose.yml
        workdir: ./HW1
        set: |
          *.cache-to=type=gha,scope=cached-stage,mode=max
          *.cache-from=type=gha,scope=cached-stage
        tags: ghcr.io/LeikRad/tqs_hw1:latest,ghcr.io/LeikRad/tqs_hw1:${{ github.sha }}