name: Deploy
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    env:
      PRODUCTION: true
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      API_KEY: ${{ secrets.API_KEY }}
    steps:
    - uses: actions/checkout@v3

    - name: Login to Github Packages
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Deploy with docker-compose
      working-directory: ./HW1
      run: |
        docker compose -f compose.prod.yml pull
        docker compose -f compose.prod.yml up FLAGS="-d --remove-orphans"
        docker container prune -f
        docker image prune -af
        docker builder prune